/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PolicyPage = {
  _id: string;
  _type: "policyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  lastUpdated?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  story?: string;
  images?: Array<
    {
      _key: string;
    } & AccessibleImage
  >;
  petInformation?: string;
  petRules?: Array<string>;
  occasions?: Array<string>;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guestName?: string;
  review?: string;
  rating?: number;
  sourceUrl?: string;
  approved?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "photo" | "video";
  photo?: AccessibleImage;
  videoUrl?: string;
  videoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: AccessibleImage;
  caption?: string;
  category?:
    | "Entrance"
    | "Lawns"
    | "Swimming Pool"
    | "Glamps"
    | "Huts"
    | "Tents"
    | "Dining"
    | "Music and Karaoke"
    | "Restrooms"
    | "Other";
  displayOrder?: number;
  featured?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AccessibleImage = {
  _type: "accessibleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Amenity = {
  _id: string;
  _type: "amenity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: string;
  description?: string;
  image?: AccessibleImage;
  icon?:
    | "leaf"
    | "water"
    | "bed"
    | "dining"
    | "music"
    | "parking"
    | "accessibility"
    | "pet";
  displayOrder?: number;
  active?: boolean;
};

export type Package = {
  _id: string;
  _type: "package";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: "Day Picnic" | "Evening Leisure" | "Overnight";
  accommodation?: "Glamp" | "Hut" | "Tent";
  summary?: string;
  cover?: AccessibleImage;
  gallery?: Array<
    {
      _key: string;
    } & AccessibleImage
  >;
  price?: number;
  currency?: string;
  pricingUnit?: "per person" | "per group" | "per stay";
  vegetarianPrice?: number;
  nonVegetarianPrice?: number;
  arrival?: string;
  departure?: string;
  departureDayOffset?: number;
  inclusions?: Array<string>;
  exclusions?: Array<string>;
  rules?: Array<string>;
  displayOrder?: number;
  active?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PackageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "package";
};

export type GalleryItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "galleryItem";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroMediaType?: "image" | "video";
  hero?: AccessibleImage;
  heroVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  heading?: string;
  supportingLine?: string;
  featuredPackages?: Array<
    {
      _key: string;
    } & PackageReference
  >;
  featuredGallery?: Array<
    {
      _key: string;
    } & GalleryItemReference
  >;
  introduction?: string;
  highlights?: Array<string>;
  occasions?: Array<string>;
  dayCapacity?: number;
  overnightCapacity?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  logo?: AccessibleImage;
  shortDescription?: string;
  address?: string;
  directionsUrl?: string;
  officeContacts?: Array<{
    name?: string;
    phone?: string;
    _type: "contact";
    _key: string;
  }>;
  corporateContacts?: Array<{
    name?: string;
    phone?: string;
    _type: "contact";
    _key: string;
  }>;
  whatsapp?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: AccessibleImage;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PolicyPage
  | AboutPage
  | Testimonial
  | SanityFileAssetReference
  | GalleryItem
  | SanityImageAssetReference
  | AccessibleImage
  | Amenity
  | Package
  | Slug
  | PackageReference
  | GalleryItemReference
  | HomePage
  | SiteSettings
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{siteName,shortDescription,logo,address,directionsUrl,officeContacts[]{name,phone},corporateContacts[]{name,phone},whatsapp,socialLinks[]{label,url},seo{title,description,image}}
export type SETTINGS_QUERY_RESULT = {
  siteName: string | null;
  shortDescription: string | null;
  logo: AccessibleImage | null;
  address: string | null;
  directionsUrl: string | null;
  officeContacts: Array<{
    name: string | null;
    phone: string | null;
  }> | null;
  corporateContacts: Array<{
    name: string | null;
    phone: string | null;
  }> | null;
  whatsapp: string | null;
  socialLinks: Array<{
    label: string | null;
    url: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: AccessibleImage | null;
  } | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{heading,supportingLine,hero,heroMediaType,"heroVideoUrl":heroVideo.asset->url,introduction,highlights,occasions,dayCapacity,overnightCapacity,featuredPackages[]-> [active == true]{_id,name,slug,summary,cover},featuredGallery[]->{_id,kind,photo,caption,category,videoUrl,"videoFileUrl":videoFile.asset->url,poster}}
export type HOME_QUERY_RESULT = {
  heading: string | null;
  supportingLine: string | null;
  hero: AccessibleImage | null;
  heroMediaType: "image" | "video" | null;
  heroVideoUrl: string | null;
  introduction: string | null;
  highlights: Array<string> | null;
  occasions: Array<string> | null;
  dayCapacity: number | null;
  overnightCapacity: number | null;
  featuredPackages: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    summary: string | null;
    cover: AccessibleImage | null;
  }> | null;
  featuredGallery: Array<{
    _id: string;
    kind: "photo" | "video" | null;
    photo: AccessibleImage | null;
    caption: string | null;
    category:
      | "Dining"
      | "Entrance"
      | "Glamps"
      | "Huts"
      | "Lawns"
      | "Music and Karaoke"
      | "Other"
      | "Restrooms"
      | "Swimming Pool"
      | "Tents"
      | null;
    videoUrl: string | null;
    videoFileUrl: string | null;
    poster: AccessibleImage | null;
  }> | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: PACKAGES_QUERY
// Query: *[_type == "package" && active == true] | order(displayOrder asc){_id,name,slug,category,accommodation,summary,cover,gallery,price,currency,pricingUnit,vegetarianPrice,nonVegetarianPrice,arrival,departure,departureDayOffset,inclusions,exclusions,rules,seo{title,description,image}}
export type PACKAGES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  category: "Day Picnic" | "Evening Leisure" | "Overnight" | null;
  accommodation: "Glamp" | "Hut" | "Tent" | null;
  summary: string | null;
  cover: AccessibleImage | null;
  gallery: Array<
    {
      _key: string;
    } & AccessibleImage
  > | null;
  price: number | null;
  currency: string | null;
  pricingUnit: "per group" | "per person" | "per stay" | null;
  vegetarianPrice: number | null;
  nonVegetarianPrice: number | null;
  arrival: string | null;
  departure: string | null;
  departureDayOffset: number | null;
  inclusions: Array<string> | null;
  exclusions: Array<string> | null;
  rules: Array<string> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: AccessibleImage | null;
  } | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: AMENITIES_QUERY
// Query: *[_type == "amenity" && active == true] | order(displayOrder asc){_id,name,category,description,image,icon}
export type AMENITIES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  category: string | null;
  description: string | null;
  image: AccessibleImage | null;
  icon:
    | "accessibility"
    | "bed"
    | "dining"
    | "leaf"
    | "music"
    | "parking"
    | "pet"
    | "water"
    | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: GALLERY_QUERY
// Query: *[_type == "galleryItem"] | order(displayOrder asc){_id,kind,photo,videoUrl,"videoFileUrl":videoFile.asset->url,poster,caption,category,featured}
export type GALLERY_QUERY_RESULT = Array<{
  _id: string;
  kind: "photo" | "video" | null;
  photo: AccessibleImage | null;
  videoUrl: string | null;
  videoFileUrl: string | null;
  poster: AccessibleImage | null;
  caption: string | null;
  category:
    | "Dining"
    | "Entrance"
    | "Glamps"
    | "Huts"
    | "Lawns"
    | "Music and Karaoke"
    | "Other"
    | "Restrooms"
    | "Swimming Pool"
    | "Tents"
    | null;
  featured: boolean | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && approved == true]{_id,guestName,review,rating,sourceUrl}
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  guestName: string | null;
  review: string | null;
  rating: number | null;
  sourceUrl: string | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{story,images,petInformation,petRules,occasions}
export type ABOUT_QUERY_RESULT = {
  story: string | null;
  images: Array<
    {
      _key: string;
    } & AccessibleImage
  > | null;
  petInformation: string | null;
  petRules: Array<string> | null;
  occasions: Array<string> | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: POLICY_QUERY
// Query: *[_type == "policyPage" && slug.current == $slug][0]{title,body,lastUpdated}
export type POLICY_QUERY_RESULT = {
  title: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  lastUpdated: string | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{siteName,shortDescription,logo,address,directionsUrl,officeContacts[]{name,phone},corporateContacts[]{name,phone},whatsapp,socialLinks[]{label,url},seo{title,description,image}}': SETTINGS_QUERY_RESULT;
    '*[_type == "homePage" && _id == "homePage"][0]{heading,supportingLine,hero,heroMediaType,"heroVideoUrl":heroVideo.asset->url,introduction,highlights,occasions,dayCapacity,overnightCapacity,featuredPackages[]-> [active == true]{_id,name,slug,summary,cover},featuredGallery[]->{_id,kind,photo,caption,category,videoUrl,"videoFileUrl":videoFile.asset->url,poster}}': HOME_QUERY_RESULT;
    '*[_type == "package" && active == true] | order(displayOrder asc){_id,name,slug,category,accommodation,summary,cover,gallery,price,currency,pricingUnit,vegetarianPrice,nonVegetarianPrice,arrival,departure,departureDayOffset,inclusions,exclusions,rules,seo{title,description,image}}': PACKAGES_QUERY_RESULT;
    '*[_type == "amenity" && active == true] | order(displayOrder asc){_id,name,category,description,image,icon}': AMENITIES_QUERY_RESULT;
    '*[_type == "galleryItem"] | order(displayOrder asc){_id,kind,photo,videoUrl,"videoFileUrl":videoFile.asset->url,poster,caption,category,featured}': GALLERY_QUERY_RESULT;
    '*[_type == "testimonial" && approved == true]{_id,guestName,review,rating,sourceUrl}': TESTIMONIALS_QUERY_RESULT;
    '*[_type == "aboutPage" && _id == "aboutPage"][0]{story,images,petInformation,petRules,occasions}': ABOUT_QUERY_RESULT;
    '*[_type == "policyPage" && slug.current == $slug][0]{title,body,lastUpdated}': POLICY_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
